### ISSUE TITLE
TypeError: cu is not a function in production build

### ISSUE THREAD

**Issue by just-tom** [inertiaui/modal#66]
Hi,

In development the modals work perfectly however after running `npm run build` I am receiving an error:

`Show-DU11Yx6H.js:4 Uncaught (in promise) TypeError: cu is not a function
    at du (Show-DU11Yx6H.js:4:10908)
    at Show-DU11Yx6H.js:4:11781` 

It seems to be something to do with a resolveComponent function in `modalStack.js:236` cu being the name of the compiled resolveComponent function.

 I have tried both ways of mounting the app and both install methods for the frontend package, but all with the same outcome. Here is my app.js as it stands:

```
import './bootstrap';
import '../css/app.css';

import { createApp, h } from 'vue';
import { createInertiaApp } from '@inertiajs/vue3';
import { resolvePageComponent } from 'laravel-vite-plugin/inertia-helpers';
import { ZiggyVue } from '../../vendor/tightenco/ziggy';
import Toast from "vue-toastification";
import "vue-toastification/dist/index.css";
import '@inertiaui/table-vue/style.css'
import { renderApp } from '@inertiaui/modal-vue'


const appName = import.meta.env.VITE_APP_NAME || 'Laravel';

createInertiaApp({
    title: (title) => `${title} - ${appName}`,
    resolve: (name) => resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob('./Pages/**/*.vue')),
    setup({ el, App, props, plugin }) {
        return createApp({ render: renderApp(App, props) })
            .use(plugin)
            .use(ZiggyVue)
            .use(Toast, {
                transition: "Vue-Toastification__fade",
                maxToasts: 20,
                newestOnTop: true,
                timeout: 3000
            })
            .mount(el);
    },
    progress: {
        color: '#4B5563',
    },
});

```

I am using in conjunction with InertiaUI Table package. My Show.vue file is also very simple which is where this error seems to be stemming from:

```
<script setup>
import AppLayout from "@/Layouts/AppLayout.vue";
import { Table } from '@inertiaui/table-vue'
import * as Icons from '@heroicons/vue/24/outline'

const props = defineProps({
    integration: Object,
    logs: Object|null
})

function resolveIcon(icon) {
    return Icons[icon]
}
</script>

<template>
    <AppLayout :title="integration.name">
        <div class="mx-auto max-w-7xl mt-8 space-y-8">
            <div>
                <h2 class="text-lg block font-medium text-blue-sing-900 dark:text-blue-sing-100">
                    API Logs</h2>
                <Table class="mt-6" :resource="logs" :icon-resolver="resolveIcon"/>
            </div>
        </div>
    </AppLayout>
</template>

<style scoped>

</style>
```

Any help would be greatly appreciated. Thanks!

**Comment by pascalbaljet** [comment]
Could you try upgrading the Modal package to v0.14 and the Table package to v2.4.1? These updates resolve similar problems. A bit brutal, but try removing the `node_modules` folder and reinstalling if it doesn't work.

**Comment by just-tom** [comment]
Worked perfectly @pascalbaljet - thank you!
